springboot:
  enabled: false
  postgresql:
    host: {{ include "postgres-chart.fullname" . }} # Link to the PostgreSQL service
    port: 5432
    database: trade
    username: postgres
    password: root

