apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kprbackend.fullname" . }}
  labels:
    {{- include "kprbackend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kprbackend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kprbackend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kprbackend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
           - name: SPRING_DATASOURCE_URL
             value: "jdbc:postgresql://{{ .Values.kprbackend.database.host }}:{{ .Values.kprbackend.database.port }}/{{ .Values.kprbackend.database.name }}"
           - name: SPRING_DATASOURCE_USERNAME
             value: {{ .Values.kprbackend.database.username }}
           - name: SPRING_DATASOURCE_PASSWORD
             value: {{ .Values.kprbackend.database.password }}
        
        
          ports:
            - name: http
              containerPort: 9044
              protocol: TCP
      #    livenessProbe:
      #     httpGet:
      #       path: /
      #   readinessProbe:
       #     httpGet:
       #       path: /
        #      port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
