name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-container:
    runs-on: self-hosted
 #   env:
    #  DOCKER_REPOSITORY: ${{ secrets.DOCKER_USER_NAME }}
    #  IMAGE_NAME: trademanager
     # IMAGE_TAG: ${{ github.run_number }}
     
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u xyloincadmin -p ${{ secrets.DOCKERPASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG="${GITHUB_RUN_NUMBER}"
          docker buildx create --use
          docker buildx build -t xyloincadmin/trademanager:$IMAGE_TAG . --push
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          DOCKER_BUILDKIT: 1
          DOCKERHUB_USERNAME: xyloincadmin
      -
        name: Checkout
        uses: actions/checkout@v3
     
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
         charts_dir: /kprbackend
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"        

      - name: Configure kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Check if Helm release exists & Install or Upgrade Helm Chart
        id: check_release
        run: |
           RELEASE_NAME=xy-backend
           if helm get $RELEASE_NAME > /dev/null 2>&1; then
               echo "Helm release $RELEASE_NAME already exists."
                helm upgrade $RELEASE_NAME kprbackend -f values.yaml 
               echo "::set-output name=release_exists::true"
           else
               echo "Helm release $RELEASE_NAME does not exist."
                helm install $RELEASE_NAME kprchat /kprbackend -f values.yaml 
               echo "::set-output name=release_exists::false"
           fi
     

     

       
