name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-container:
    runs-on: self-hosted
    env:
    #  DOCKER_REPOSITORY: ${{ secrets.DOCKER_USER_NAME }}
    #  IMAGE_NAME: trademanager
     # IMAGE_TAG: ${{ github.run_number }}
     
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u xyloincadmin -p ${{ secrets.DOCKERPASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG="${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          docker buildx create --use
          docker buildx build -t xyloincadmin/trademanager:$IMAGE_TAG . --push
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          DOCKER_BUILDKIT: 1
          DOCKERHUB_USERNAME: xyloincadmin
