name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-container:
    runs-on: self-hosted
 #   env:
    #  DOCKER_REPOSITORY: ${{ secrets.DOCKER_USER_NAME }}
    #  IMAGE_NAME: trademanager
     # IMAGE_TAG: ${{ github.run_number }}
     
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKER_USER_NAME }}
         password: ${{ secrets.DOCKER_REPOSITORY_PASSWORD }}

      - name: Build and push Docker image
        run: |
           IMAGE_NAME="xyloincadmin/trademanager"
           TAG="github-run-${{ github.run_number }}"

            docker build -t $IMAGE_NAME:$TAG . --no-cache
            docker push $IMAGE_NAME:$TAG
          
      -
        name: Checkout
        uses: actions/checkout@v3
     
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
         charts_dir: /kprbackend
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"        

      - name: Configure kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
      - name: Upgrade or Install Helm release
        run: |
             RELEASE_NAME="xy-erp"
             if helm list -q | grep -q $RELEASE_NAME; then
                echo "Upgrading Helm release $RELEASE_NAME..."
                helm upgrade $RELEASE_NAME kprbackend  --set image.tag="${GITHUB_RUN_NUMBER}"
             else
                echo "Installing Helm release $RELEASE_NAME..."
                helm install $RELEASE_NAME kprbackend 
             fi
     

     

       
